### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by marshtompsxd** [anvil-verifier/anvil#560]
VReplicaSet:
- [ ] Implement an admission controller for object validation
- [ ] Implement reconciliation features:
  - [ ] Skip deleting VReplicaSet
  - [ ] Pod adoption and release
  - [ ] Manage status
- [ ] Finish ESR proof
